import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import crypto from 'node:crypto';
import { createClient } from '@supabase/supabase-js';
import type { Observation } from '../shared/types.js';
const app=express(); const PORT=Number(process.env.PORT||8787);
app.use(cors({origin:process.env.ALLOWED_ORIGIN||true})); app.use(express.json({limit:'4mb'}));
const supabase=process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY?createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY):null;
const memory:any={validation:{enabled:true,minRate:140000,maxRate:165000,warningOnly:false,anomalyEnabled:true,anomalyDelta:3000,anomalyWindowMinutes:10,freshnessMinutes:180},publishing:{enabled:false,livePriceEnabled:true,minConfidence:.8,minIndependentSources:1,maxPostsPerHour:30,quietStart:'23:00',quietEnd:'08:00',radarEnabled:true,radarDelta:250,radarWindowMinutes:60,openTime:'10:00',closeTime:'17:30'},market:{defaultCity:'SULAYMANIYAH',headlineCategory:'STANDARD_MIX',freshnessMinutes:180,radarDelta:250,radarWindowMinutes:60},polling:{enabled:true,peakIntervalMinutes:2,normalIntervalMinutes:5,nightIntervalMinutes:15,timezone:'Asia/Baghdad',peakStart:'10:00',peakEnd:'18:00'},ai:{enabled:true,provider:'groq',endpoint:'https://api.groq.com/openai/v1/chat/completions',model:'llama-3.3-70b-versatile',temperature:0,maxTokens:2200},commodities:{silverKgEnabled:false,dubaiLira72gEnabled:false,silverMinConfidence:.75,liraMinConfidence:.75}};
async function cfg(k:string){if(!supabase)return memory[k]??{};const{data}=await supabase.from('app_config').select('value').eq('key',k).maybeSingle();return data?.value??memory[k]??{}}
async function setCfg(k:string,v:any){memory[k]=v;if(supabase)await supabase.from('app_config').upsert({key:k,value:v,updated_at:new Date().toISOString()},{onConflict:'key'});return v}
async function rows(t:string,limit=300){if(!supabase)return[];const{data,error}=await supabase.from(t).select('*').order('created_at',{ascending:false}).limit(limit);if(error)throw error;return data||[]}
async function insert(t:string,v:any){if(!supabase)return{...v,id:crypto.randomUUID(),created_at:new Date().toISOString()};const{data,error}=await supabase.from(t).insert(v).select('*').single();if(error)throw error;return data}
async function update(t:string,id:string,v:any){if(!supabase)return{id,...v};const{data,error}=await supabase.from(t).update(v).eq('id',id).select('*').single();if(error)throw error;return data}
async function remove(t:string,id:string){if(!supabase)return true;const{error}=await supabase.from(t).delete().eq('id',id);if(error)throw error;return true}
async function log(level:string,kind:string,message:string,meta:any={}){console.log(`[${level}] ${kind}: ${message}`);if(supabase)await supabase.from('logs').insert({level,kind,message,meta})}
const digits:any={'٠':'0','١':'1','٢':'2','٣':'3','٤':'4','٥':'5','٦':'6','٧':'7','٨':'8','٩':'9','۰':'0','۱':'1','۲':'2','۳':'3','۴':'4','۵':'5','۶':'6','۷':'7','۸':'8','۹':'9'};const norm=(s:string)=>s.replace(/[٠-٩۰-۹]/g,c=>digits[c]||c).replace(/[٬،]/g,',');
const cityRules:[RegExp,string][]=[[/سلێمانی|سليمانيه|السليمانية|sulaymaniyah|slemani/i,'SULAYMANIYAH'],[/هەولێر|اربيل|أربيل|erbil/i,'ERBIL'],[/بغداد|baghdad/i,'BAGHDAD'],[/مووسڵ|الموصل|نینەوا|نينوى|mosul|nineveh/i,'MOSUL'],[/بەسرە|البصرة|basra/i,'BASRA'],[/کەرکووک|كركوك|kirkuk/i,'KIRKUK'],[/ڕانیە|رانیە|رانية|ranya/i,'RANYA'],[/دهۆک|دهوك|duhok/i,'DUHOK']];const city=(s:string)=>cityRules.find(([r])=>r.test(s))?.[1]||'UNKNOWN';
const layer=(s:string)=>/الكفاح|كفاح|الحارثية|حارثية|بورصة|بورص/i.test(s)?'BOURSE':/صيرفات|صيرفة|مكاتب/i.test(s)?'EXCHANGE_OFFICES':/كروبات|کروبات|trader/i.test(s)?'TRADER_GROUPS':/بازار|بازاڕ|سوق|market/i.test(s)?'LOCAL_MARKET':'UNKNOWN';
function rate(raw:string){const s=norm(raw).replace(/\s/g,'').replace(/\$/g,'');if(/^\d{1,3}\.\d{2,3}$/.test(s))return Math.round(Number(s)*1000);if(/^\d{1,3},\d{3}$/.test(s))return Number(s.replace(',',''));if(/^\d{6,7}$/.test(s))return Number(s);if(/^\d{3,4}$/.test(s))return Number(s)*100;const n=Number(s.replace(/,/g,''));return Number.isFinite(n)?n:null}
function extract(text:string):Observation[]{const t=norm(text),out:Observation[]=[];let currentCity='UNKNOWN',currentLayer='UNKNOWN',offset=0;for(const line0 of t.split(/\r?\n/)){const line=line0.trim();const c=city(line);if(c!=='UNKNOWN')currentCity=c;const l=layer(line);if(l!=='UNKNOWN')currentLayer=l;if(/\b(?:80|18|4)\b/.test(line)&&/شین|شين|سپي|سپی|پێنجی|خمسات|ستاندارد/i.test(line)&&!/(14\d|15\d|16\d)[,.\s]\d{3}/.test(line)){offset+=line0.length+1;continue}const m=/(?:100\s*\$|\$\s*100|دولار|دۆلار|USD|=|:|→|->)\D{0,20}([0-9][0-9,.\s]{3,})/i.exec(line)||/([0-9][0-9,.\s]{5,})/.exec(line);if(m){const n=rate(m[1]);if(n){const s=line.indexOf(m[1]);const role=/(بيع|فرۆشتن|فروش|فرۆش)/i.test(line)?'SELL':/(شراء|کڕین|کڕ)/i.test(line)?'BUY':'UNKNOWN';const time=/(غد|غداً|tomorrow|forecast|پێشبینی)/i.test(line)?'FORECAST':/(أمس|دوێنێ|yesterday)/i.test(line)?'HISTORICAL':'CURRENT';out.push({city:currentCity,market_layer:currentLayer,currency:'IQD',quote_currency:'USD',rate:n,rate_role:role,numeric_role:'RATE',time_context:time,confidence:.9,evidence_text:line.slice(s,s+m[1].length),evidence_start:offset+s,evidence_end:offset+s+m[1].length,status:'CANDIDATE',observed_at:new Date().toISOString(),dollar_category_normalized:'STANDARD_MIX'} as Observation)}}offset+=line0.length+1}return out}
const fp=(o:any)=>crypto.createHash('sha256').update(JSON.stringify([o.city,o.market_layer,o.rate,o.rate_role,o.time_context,o.evidence_text])).digest('hex');
app.get('/api/health',async(_q,r)=>r.json({ok:true,supabase:!!supabase,telegramConfigured:!!process.env.TELEGRAM_SESSION,mtprotoConfigured:!!(process.env.TELEGRAM_API_ID&&process.env.TELEGRAM_API_HASH&&process.env.TELEGRAM_SESSION),botConfigured:!!process.env.TELEGRAM_BOT_TOKEN,timezone:'Asia/Baghdad',time:new Date().toISOString()}));
app.get('/api/config/:key',async(q,r)=>{try{r.json(await cfg(q.params.key))}catch(e:any){r.status(500).json({error:e.message})}});app.put('/api/config/:key',async(q,r)=>{try{r.json(await setCfg(q.params.key,q.body))}catch(e:any){r.status(500).json({error:e.message})}});
for(const t of ['sources','channels','observations','quarantine','logs','terminology','templates','schedules','published_posts','commodity_observations'])app.get('/api/'+t,async(_q,r)=>{try{r.json(await rows(t))}catch(e:any){r.status(500).json({error:e.message})}});
for(const [route,table] of [['sources','sources'],['channels','channels'],['terminology','terminology'],['templates','templates'],['schedules','schedules']] as const){app.post('/api/'+route,async(q,r)=>{try{r.status(201).json(await insert(table,q.body))}catch(e:any){r.status(500).json({error:e.message})}});app.put('/api/'+route+'/:id',async(q,r)=>{try{r.json(await update(table,q.params.id,q.body))}catch(e:any){r.status(500).json({error:e.message})}});app.delete('/api/'+route+'/:id',async(q,r)=>{try{await remove(table,q.params.id);r.json({ok:true})}catch(e:any){r.status(500).json({error:e.message})}})}
app.get('/api/config/bot',async(_q,r)=>r.json({configured:!!process.env.TELEGRAM_BOT_TOKEN,connected:false,lastCheck:null}));app.post('/api/telegram/test',async(_q,r)=>r.json({connected:!!process.env.TELEGRAM_BOT_TOKEN,configured:!!process.env.TELEGRAM_BOT_TOKEN,lastCheck:new Date().toISOString()}));
app.post('/api/test/extract',async(q,r)=>r.json({items:extract(String(q.body?.text||'')),normalized:norm(String(q.body?.text||''))}));
app.post('/api/collector/ingest',async(q,r)=>{try{if(process.env.INGEST_SECRET&&q.headers['x-ingest-secret']!==process.env.INGEST_SECRET)return r.status(401).json({error:'unauthorized'});const text=String(q.body?.text||q.body?.message?.text||q.body?.message?.caption||'');if(!text)return r.status(400).json({error:'empty message'});const username=String(q.body?.chat?.username||'').replace(/^@/,'');let source:any=null;if(supabase&&username)source=(await supabase.from('sources').select('*').eq('username','@'+username).maybeSingle()).data;let raw:any=null;if(supabase)raw=(await supabase.from('raw_messages').insert({source_id:source?.id,telegram_message_id:q.body?.message?.message_id,message_text:text,telegram_url:q.body?.telegram_url,posted_at:q.body?.message?.date?new Date(Number(q.body.message.date)*1000).toISOString():new Date().toISOString(),raw_payload:q.body}).select('*').single()).data;const v=await cfg('validation');const items=extract(text);const saved:any[]=[];for(const o of items){o.source_id=source?.id;o.raw_message_id=raw?.id;o.validation_reasons=[];if(Number(o.rate)<Number(v.minRate)||Number(o.rate)>Number(v.maxRate))o.validation_reasons.push('RATE_OUT_OF_RANGE');if(o.time_context==='FORECAST')o.validation_reasons.push('FORECAST_NOT_CURRENT');o.status=o.validation_reasons.length?'QUARANTINED':'VALID';(o as any).fingerprint=fp(o);if(supabase){const exists=(await supabase.from('observations').select('id').eq('fingerprint',(o as any).fingerprint).maybeSingle()).data;if(!exists){const row=(await supabase.from('observations').insert(o).select('*').single()).data;if(row)saved.push(row);if(o.status==='QUARANTINED'&&row)await supabase.from('quarantine').insert({observation_id:row.id,reason:o.validation_reasons.join(','),payload:o})}}else saved.push(o)}await log('INFO','INGEST','Accepted Telegram message',{source:username,count:items.length});r.json({accepted:true,source:username,count:items.length,items,saved})}catch(e:any){await log('ERROR','INGEST',e.message);r.status(500).json({error:e.message})}});
app.put('/api/quarantine/:id',async(q,r)=>{try{r.json(await update('quarantine',q.params.id,{status:String(q.body?.status||'REVIEWED'),reviewed_at:new Date().toISOString()}))}catch(e:any){r.status(500).json({error:e.message})}});
app.get('/api/market/snapshot',async(q,r)=>{try{if(!supabase)return r.json({groups:[],observations:[]});const cf=String(q.query.city||'ALL'),lf=String(q.query.layer||'ALL');const{data,error}=await supabase.from('observations').select('*').eq('status','VALID').eq('time_context','CURRENT').order('observed_at',{ascending:false}).limit(1000);if(error)throw error;const rr=(data||[]).filter((x:any)=>(cf==='ALL'||x.city===cf)&&(lf==='ALL'||x.market_layer===lf));const g:any={};for(const x of rr){const k=[x.city,x.market_layer,x.rate_role].join('|');(g[k]??=[]).push(Number(x.rate))}const groups=Object.entries(g).map(([key,v]:any)=>{v.sort((a:number,b:number)=>a-b);return{key,city:key.split('|')[0],market_layer:key.split('|')[1],rate_role:key.split('|')[2],median:v[Math.floor(v.length/2)],min:v[0],max:v[v.length-1],range:v[v.length-1]-v[0],count:v.length}});r.json({groups,observations:rr.slice(0,200)})}catch(e:any){r.status(500).json({error:e.message})}});
app.get('/api/analytics',async(_q,r)=>{try{if(!supabase)return r.json({messageCount:0,observationCount:0,validCount:0,quarantineCount:0,publishedCount:0,sources:[]});const[o,q,raw,pub,s]=await Promise.all([supabase.from('observations').select('status,source_id,confidence,observed_at'),supabase.from('quarantine').select('id',{count:'exact',head:true}),supabase.from('raw_messages').select('id',{count:'exact',head:true}),supabase.from('published_posts').select('id',{count:'exact',head:true}),supabase.from('sources').select('*')]);const data=o.data||[];const sources=(s.data||[]).map((x:any)=>{const a=data.filter((z:any)=>z.source_id===x.id);return{username:x.username,title:x.title,count:a.length,valid:a.filter((z:any)=>z.status==='VALID').length,validity:a.length?100*a.filter((z:any)=>z.status==='VALID').length/a.length:0,confidence:a.length?a.reduce((n:number,z:any)=>n+Number(z.confidence||0),0)/a.length:0,last:a.sort((a:any,b:any)=>new Date(b.observed_at).getTime()-new Date(a.observed_at).getTime())[0]?.observed_at||null}});r.json({messageCount:raw.count||0,observationCount:data.length,validCount:data.filter((x:any)=>x.status==='VALID').length,quarantineCount:q.count||0,publishedCount:pub.count||0,sources})}catch(e:any){r.status(500).json({error:e.message})}});
app.get('/api/analytics/history',async(q,r)=>{try{if(!supabase)return r.json([]);const hours=Math.min(Number(q.query.hours||24),2160);const since=new Date(Date.now()-hours*3600000).toISOString();const{data,error}=await supabase.from('observations').select('city,market_layer,rate,rate_role,observed_at').eq('status','VALID').gte('observed_at',since).order('observed_at',{ascending:true}).limit(5000);if(error)throw error;r.json(data||[])}catch(e:any){r.status(500).json({error:e.message})}});
app.post('/api/ai/editorial',async(_q,r)=>{const a=await cfg('ai');r.json({configured:!!process.env.GROQ_API_KEY,enabled:!!a.enabled,model:a.model||'llama-3.3-70b-versatile'})});
app.get('/api/backup/config',async(_q,r)=>{const o:any={};for(const k of ['validation','polling','publishing','market','ai','commodities'])o[k]=await cfg(k);r.setHeader('Content-Disposition','attachment; filename="nova-dollar-config.json"');r.json(o)});
if(process.env.NODE_ENV!=='vercel')app.listen(PORT,()=>console.log(`Nova Dollar API listening on ${PORT}`));
export default app;
