import 'dotenv/config';
import express from 'express';import cors from 'cors';import crypto from 'node:crypto';import {createClient} from '@supabase/supabase-js';
import type {Observation} from '../shared/types.js';
const app=express();const PORT=Number(process.env.PORT||8787);app.use(cors({origin:process.env.ALLOWED_ORIGIN||'http://localhost:5173'}));app.use(express.json({limit:'4mb'}));
const supabase=process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY?createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY):null;
const memory:any={validation:{enabled:true,minRate:140000,maxRate:165000,anomalyDelta:3000,anomalyWindowMinutes:10,freshnessMinutes:180},publishing:{enabled:false,livePriceEnabled:true,minConfidence:.8,minIndependentSources:1,radarEnabled:true,radarDelta:250,radarWindowMinutes:60,openTime:'10:00',closeTime:'17:30'},market:{defaultCity:'SULAYMANIYAH',headlineCategory:'STANDARD_MIX',freshnessMinutes:180,radarDelta:250,radarWindowMinutes:60},polling:{enabled:true,peakIntervalMinutes:2,normalIntervalMinutes:5,nightIntervalMinutes:15,timezone:'Asia/Baghdad',peakStart:'10:00',peakEnd:'18:00'},ai:{enabled:true,provider:'groq',endpoint:'https://api.groq.com/openai/v1/chat/completions',model:'llama-3.3-70b-versatile',temperature:0,maxTokens:2200},commodities:{silverKgEnabled:false,dubaiLira72gEnabled:false,silverMinConfidence:.75,liraMinConfidence:.75}};
async function cfg(k:string){if(!supabase)return memory[k];const{data}=await supabase.from('app_config').select('value').eq('key',k).maybeSingle();return data?.value??memory[k]}async function setCfg(k:string,v:any){memory[k]=v;if(supabase)await supabase.from('app_config').upsert({key:k,value:v,updated_at:new Date().toISOString()},{onConflict:'key'});return v}async function select(t:string,limit=200){if(!supabase)return[];const{data}=await supabase.from(t).select('*').order('created_at',{ascending:false}).limit(limit);return data||[]}
const digits:any={'٠':'0','١':'1','٢':'2','٣':'3','٤':'4','٥':'5','٦':'6','٧':'7','٨':'8','٩':'9','۰':'0','۱':'1','۲':'2','۳':'3','۴':'4','۵':'5','۶':'6','۷':'7','۸':'8','۹':'9'};const norm=(s:string)=>s.replace(/[٠-٩۰-۹]/g,c=>digits[c]||c).replace(/[٬،]/g,',');
function rate(raw:string){const s=norm(raw).replace(/\s/g,'').replace(/\$/g,'');if(/^\d{1,3}\.\d{2,3}$/.test(s))return Math.round(Number(s)*1000);if(/^\d{1,3},\d{3}$/.test(s))return Number(s.replace(',',''));if(/^\d{6,7}$/.test(s))return Number(s);if(/^\d{3,4}$/.test(s))return Number(s)*100;const n=Number(s.replace(/,/g,''));return Number.isFinite(n)?n:null}
const cities:[RegExp,string][]=[[/سلێمانی|سليمانيه|السليمانية|sulaymaniyah|slemani/i,'SULAYMANIYAH'],[/هەولێر|اربيل|أربيل|erbil/i,'ERBIL'],[/بغداد|baghdad/i,'BAGHDAD'],[/مووسڵ|الموصل|نینەوا|نينوى|mosul|nineveh/i,'MOSUL'],[/بەسرە|البصرة|basra/i,'BASRA'],[/کەرکووک|كركوك|kirkuk/i,'KIRKUK'],[/ڕانیە|رانیە|رانية|ranya/i,'RANYA'],[/دهۆک|دهوك|duhok/i,'DUHOK']];
const city=(s:string)=>cities.find(([r])=>r.test(s))?.[1];const layer=(s:string)=>/الكفاح|كفاح|الحارثية|حارثية|بورصة|بورص/i.test(s)?'BOURSE':/صيرفات|مكاتب/i.test(s)?'EXCHANGE_OFFICES':/كروبات|کروبات|trader/i.test(s)?'TRADER_GROUPS':/بازار|بازاڕ|سوق|market/i.test(s)?'LOCAL_MARKET':'UNKNOWN';
function extract(text:string):Observation[]{const t=norm(text),out:Observation[]=[];let currentCity='UNKNOWN',currentLayer='UNKNOWN',offset=0;for(const line0 of t.split(/\r?\n/)){const line=line0.trim();const c=city(line);if(c)currentCity=c;const l=layer(line);if(l!=='UNKNOWN')currentLayer=l;if(/\b(?:80|18|4)\b/.test(line)&&/شین|شين|سپي|سپی|پێنجی|خمسات|ستاندارد/i.test(line)&&!/(15\d|16\d)[,.\s]\d{3}/.test(line)){offset+=line0.length+1;continue}const m=/(?:100\s*\$|\$\s*100|دولار|دۆلار|USD|=|:|→|->)\D{0,20}([0-9][0-9,.\s]{3,})/i.exec(line)||/([0-9][0-9,.\s]{5,})/.exec(line);if(m){const n=rate(m[1]);if(n){const s=line.indexOf(m[1]);const label=/(بيع|فرۆشتن|فروش)/i.test(line)?'SELL':/(شراء|کڕین)/i.test(line)?'BUY':'UNKNOWN';out.push({city:currentCity,market_layer:currentLayer,currency:'IQD',quote_currency:'USD',rate:n,rate_role:label,numeric_role:'RATE',time_context:/غد|tomorrow|forecast|پێشبینی/i.test(line)?'FORECAST':/أمس|دوێنێ|yesterday/i.test(line)?'HISTORICAL':'CURRENT',confidence:.9,evidence_text:line.slice(s,s+m[1].length),evidence_start:offset+s,evidence_end:offset+s+m[1].length,status:'CANDIDATE',observed_at:new Date().toISOString(),dollar_category_normalized:'STANDARD_MIX'});}}offset+=line0.length+1}return out}
function fp(o:any){return crypto.createHash('sha256').update(JSON.stringify([o.city,o.market_layer,o.rate,o.rate_role,o.evidence_text,o.observed_at?.slice(0,16)])).digest('hex')}
app.get('/api/health',async(_q,r)=>r.json({ok:true,supabase:!!supabase,telegramConfigured:!!process.env.TELEGRAM_SESSION,timezone:'Asia/Baghdad',time:new Date().toISOString()}));app.get('/api/config/:key',async(q,r)=>r.json(await cfg(q.params.key)));app.put('/api/config/:key',async(q,r)=>r.json(await setCfg(q.params.key,q.body)));
for(const t of ['sources','channels','observations','quarantine','logs','terminology','templates','schedules'])app.get('/api/'+t,async(_q,r)=>r.json(await select(t)));
app.post('/api/test/extract',async(q,r)=>r.json({items:extract(String(q.body?.text||''))}));app.post('/api/collector/ingest',async(q,r)=>{if(process.env.INGEST_SECRET&&q.headers['x-ingest-secret']!==process.env.INGEST_SECRET)return r.status(401).json({error:'unauthorized'});const text=String(q.body?.text||q.body?.message?.text||'');if(!text)return r.status(400).json({error:'empty message'});let raw:any=null;if(supabase){const z=await supabase.from('raw_messages').insert({message_text:text,raw_payload:q.body,posted_at:new Date().toISOString()}).select('id').maybeSingle();raw=z.data}const v=await cfg('validation');const items=extract(text);for(const o of items){o.raw_message_id=raw?.id;o.validation_reasons=[];if(Number(o.rate)<v.minRate||Number(o.rate)>v.maxRate)o.validation_reasons.push('RATE_OUT_OF_RANGE');if(o.time_context==='FORECAST')o.validation_reasons.push('FORECAST_NOT_CURRENT');o.status=o.validation_reasons.length?'QUARANTINED':'VALID';(o as any).fingerprint=fp(o);if(supabase){const exists=await supabase.from('observations').select('id').eq('fingerprint',(o as any).fingerprint).maybeSingle();if(!exists.data)await supabase.from('observations').insert(o)}}r.json({accepted:true,count:items.length,items})});
app.get('/api/analytics',async(_q,r)=>{if(!supabase)return r.json({messageCount:0,observationCount:0,validCount:0,quarantineCount:0,sources:[]});const[o,q,s]=await Promise.all([supabase.from('observations').select('status,source_id'),supabase.from('quarantine').select('*',{count:'exact',head:true}),supabase.from('sources').select('*')]);const rows=o.data||[];r.json({messageCount:rows.length,observationCount:rows.length,validCount:rows.filter(x=>x.status==='VALID').length,quarantineCount:q.count||0,sources:(s.data||[]).map((x:any)=>{const a=rows.filter((r:any)=>r.source_id===x.id);return{username:x.username,count:a.length,validity:a.length?a.filter((r:any)=>r.status==='VALID').length/a.length*100:0}})})});
app.get('/api/backup/config',async(_q,r)=>{const o:any={};for(const k of ['validation','polling','publishing','market','ai','commodities'])o[k]=await cfg(k);r.setHeader('Content-Disposition','attachment; filename="nova-dollar-config.json"').json(o)});
if(process.env.NODE_ENV!=='vercel')app.listen(PORT,()=>console.log(`Nova Dollar API listening on ${PORT}`));export default app;
