import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import crypto from 'node:crypto';
import { createClient } from '@supabase/supabase-js';

const app = express();
const PORT = Number(process.env.PORT || 8787);
app.use(cors({ origin: process.env.ALLOWED_ORIGIN || true }));
app.use(express.json({ limit: '4mb' }));
const db = process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY ? createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY) : null;

const defaults:any={validation:{enabled:true,minRate:140000,maxRate:165000,anomalyDelta:3000,anomalyWindowMinutes:10,freshnessMinutes:180},publishing:{enabled:false,livePriceEnabled:true,minConfidence:.8,minIndependentSources:1,maxPostsPerHour:30,quietStart:'23:00',quietEnd:'08:00',radarEnabled:true,radarDelta:250,radarWindowMinutes:60,openTime:'10:00',closeTime:'17:30'},market:{defaultCity:'SULAYMANIYAH',headlineCategory:'STANDARD_MIX',freshnessMinutes:180,radarDelta:250,radarWindowMinutes:60},polling:{enabled:true,peakIntervalMinutes:2,normalIntervalMinutes:5,nightIntervalMinutes:15,timezone:'Asia/Baghdad',peakStart:'10:00',peakEnd:'18:00'},ai:{enabled:true,provider:'groq',endpoint:'https://api.groq.com/openai/v1/chat/completions',model:'llama-3.3-70b-versatile',temperature:0,maxTokens:2200},commodities:{silverKgEnabled:false,dubaiLira72gEnabled:false,silverMinConfidence:.75,liraMinConfidence:.75},commands:{price:true,source:true,radar:true}};
async function cfg(k:string){if(!db)return defaults[k]??{};const {data,error}=await db.from('app_config').select('value').eq('key',k).maybeSingle();if(error)throw error;return data?.value??defaults[k]??{}}
async function setCfg(k:string,v:any){if(db){const {error}=await db.from('app_config').upsert({key:k,value:v,updated_at:new Date().toISOString()},{onConflict:'key'});if(error)throw error}defaults[k]=v;return v}
async function rows(t:string,limit=500){if(!db)return[];const {data,error}=await db.from(t).select('*').order('created_at',{ascending:false}).limit(limit);if(error)throw error;return data||[]}
async function put(t:string,v:any){if(!db)return {...v,id:crypto.randomUUID(),created_at:new Date().toISOString()};const {data,error}=await db.from(t).insert(v).select('*').single();if(error)throw error;return data}
async function patch(t:string,id:string,v:any){if(!db)return{id,...v};const {data,error}=await db.from(t).update(v).eq('id',id).select('*').single();if(error)throw error;return data}
async function del(t:string,id:string){if(!db)return true;const {error}=await db.from(t).delete().eq('id',id);if(error)throw error;return true}
async function log(level:string,kind:string,message:string,meta:any={}){console.log(`[${level}] ${kind}: ${message}`);if(db)await db.from('logs').insert({level,kind,message,meta})}

const digits:any={'٠':'0','١':'1','٢':'2','٣':'3','٤':'4','٥':'5','٦':'6','٧':'7','٨':'8','٩':'9','۰':'0','۱':'1','۲':'2','۳':'3','۴':'4','۵':'5','۶':'6','۷':'7','۸':'8','۹':'9'};
const norm=(s:string)=>s.replace(/[٠-٩۰-۹]/g,c=>digits[c]||c).replace(/[٬،]/g,',');
const cityRules:[RegExp,string][]=[[/سلێمانی|سليمانيه|السليمانية|sulaymaniyah|slemani/i,'SULAYMANIYAH'],[/هەولێر|اربيل|أربيل|erbil/i,'ERBIL'],[/بغداد|baghdad/i,'BAGHDAD'],[/مووسڵ|الموصل|نینەوا|نينوى|mosul|nineveh/i,'MOSUL'],[/بەسرە|البصرة|basra/i,'BASRA'],[/کەرکووک|كركوك|kirkuk/i,'KIRKUK'],[/ڕانیە|رانیە|رانية|ranya/i,'RANYA'],[/دهۆک|دهوك|duhok/i,'DUHOK']];
const city=(s:string)=>cityRules.find(([r])=>r.test(s))?.[1]||'UNKNOWN';
const layer=(s:string)=>/الكفاح|كفاح|الحارثية|حارثية|بورصة|بورص/i.test(s)?'BOURSE':/صيرفات|صيرفة|مكاتب|صيرفي/i.test(s)?'EXCHANGE_OFFICES':/كروبات|کروبات|trader/i.test(s)?'TRADER_GROUPS':/بازار|بازاڕ|سوق|market/i.test(s)?'LOCAL_MARKET':'UNKNOWN';
const context=(s:string)=>/غد|غداً|tomorrow|forecast|پێشبینی/i.test(s)?'FORECAST':/أمس|دوێنێ|yesterday/i.test(s)?'HISTORICAL':/پێشوو|سابق|previous/i.test(s)?'PREVIOUS':'CURRENT';
const role=(s:string)=>/(بيع|فرۆشتن|فروش|فرۆش|sell)/i.test(s)?'SELL':/(شراء|کڕین|کڕ|buy)/i.test(s)?'BUY':'UNKNOWN';
function rate(raw:string){const s=norm(raw).replace(/\s/g,'').replace(/\$/g,'');if(/^\d{1,3}\.\d{2,3}$/.test(s))return Math.round(Number(s)*1000);if(/^\d{1,3},\d{3}$/.test(s))return Number(s.replace(',',''));if(/^\d{6,7}$/.test(s))return Number(s);if(/^\d{3,4}$/.test(s))return Number(s)*100;const n=Number(s.replace(/,/g,''));return Number.isFinite(n)?n:null}
function extract(text:string){const t=norm(text),out:any[]=[];let c='UNKNOWN',l='UNKNOWN',offset=0;for(const rawLine of t.split(/\r?\n/)){const line=rawLine.trim();const cc=city(line);if(cc!=='UNKNOWN')c=cc;const ll=layer(line);if(ll!=='UNKNOWN')l=ll;if(/\b(?:80|18|4)\b/.test(line)&&/شین|شين|سپي|سپی|پێنجی|خمسات|ستاندارد/i.test(line)&&!/(14\d|15\d|16\d)[,.\s]\d{3}/.test(line)){offset+=rawLine.length+1;continue}const m=/(?:100\s*\$|\$\s*100|دولار|دۆلار|USD|=|:|→|->)\D{0,20}([0-9][0-9,.\s]{3,})/i.exec(line)||/([0-9][0-9,.\s]{5,})/.exec(line);if(m){const n=rate(m[1]);if(n){const s=line.indexOf(m[1]);out.push({city:c,market_layer:l,currency:'IQD',quote_currency:'USD',rate:n,rate_role:role(line),numeric_role:'RATE',time_context:context(line),confidence:.9,evidence_text:line.slice(s,s+m[1].length),evidence_start:offset+s,evidence_end:offset+s+m[1].length,status:'CANDIDATE',observed_at:new Date().toISOString(),dollar_category_normalized:'STANDARD_MIX'})}}offset+=rawLine.length+1}return out}
function fp(o:any){return crypto.createHash('sha256').update(JSON.stringify([o.source_id,o.city,o.market_layer,o.dollar_category_normalized,o.rate_role,o.rate,o.time_context,o.evidence_text])).digest('hex')}
function median(a:number[]){const x=[...a].sort((a,b)=>a-b);return x.length?x[Math.floor(x.length/2)]:null}

async function currentObs(cityFilter='ALL'){if(!db)return[];const v=await cfg('validation');const since=new Date(Date.now()-Number(v.freshnessMinutes||180)*60000).toISOString();const {data,error}=await db.from('observations').select('*').eq('status','VALID').eq('time_context','CURRENT').gte('observed_at',since).order('observed_at',{ascending:false}).limit(5000);if(error)throw error;return(data||[]).filter((x:any)=>cityFilter==='ALL'||x.city===cityFilter)}
async function ai(prompt:string,system:string){const c=await cfg('ai');if(!c.enabled)throw new Error('AI disabled');const provider=String(c.provider||'groq').toLowerCase();const key=provider==='openrouter'?process.env.OPENROUTER_API_KEY:process.env.GROQ_API_KEY;const endpoint=provider==='openrouter'?(process.env.OPENROUTER_ENDPOINT||'https://openrouter.ai/api/v1/chat/completions'):(c.endpoint||'https://api.groq.com/openai/v1/chat/completions');const model=provider==='openrouter'?(process.env.OPENROUTER_MODEL||c.model||'openai/gpt-4o-mini'):(c.model||'llama-3.3-70b-versatile');if(!key)throw new Error(`${provider} API key missing`);const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:JSON.stringify({model,temperature:Number(c.temperature??0),max_tokens:Number(c.maxTokens||2200),messages:[{role:'system',content:system},{role:'user',content:prompt}]})});if(!r.ok)throw new Error(`AI ${r.status}: ${await r.text()}`);const j:any=await r.json();return String(j.choices?.[0]?.message?.content||'').trim()}
async function editorial(type='LIVE'){const obs=await currentObs();if(!obs.length)return 'هیچ زانیارییەکی نوێ و پشتڕاستکراو بۆ ئەم کاتە بەردەست نییە.';const groups:any={};for(const o of obs){const k=[o.city,o.market_layer,o.rate_role].join('|');(groups[k]??=[]).push(Number(o.rate))}const summary=Object.entries(groups).map(([key,v]:any)=>({key,median:median(v),min:Math.min(...v),max:Math.max(...v),count:v.length}));return ai(`Report: ${type}\n${JSON.stringify(summary)}\nEvidence:\n${JSON.stringify(obs.slice(0,60))}`,'You are Nova Dollar editorial AI. Write natural Sorani Kurdish using ONLY verified JSON. Never invent numbers, cities, sources, movement or BUY/SELL. عرض and طلب are not BUY/SELL. Keep market layers separate. Return only publishable text.')}
async function sendTelegram(chat:string,text:string){const token=process.env.TELEGRAM_BOT_TOKEN;if(!token)throw new Error('TELEGRAM_BOT_TOKEN missing');const r=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:chat,text,parse_mode:'HTML',disable_web_page_preview:true})});if(!r.ok)throw new Error(`Telegram ${r.status}: ${await r.text()}`);return await r.json() as any}
async function publish(type:string,channel?:any){const p=await cfg('publishing');if(!p.enabled&&type!=='TEST')return{published:false,reason:'publishing disabled'};if(!db)throw new Error('Supabase not configured');const channels=await rows('channels');const ch=channel?channels.find((x:any)=>x.id===channel||x.username===channel):channels.find((x:any)=>x.enabled);if(!ch)throw new Error('No enabled publishing channel');const text=await editorial(type);const result=await sendTelegram(String(ch.chat_id||ch.username),text);await put('published_posts',{channel_id:ch.id,telegram_message_id:result.result?.message_id,text,status:'PUBLISHED'});return{published:true,channel:ch.username||ch.chat_id,message_id:result.result?.message_id,text}}

app.get('/api/health',async(_q,r)=>r.json({ok:true,supabase:!!db,telegramConfigured:!!process.env.TELEGRAM_SESSION,mtprotoConfigured:!!(process.env.TELEGRAM_API_ID&&process.env.TELEGRAM_API_HASH&&process.env.TELEGRAM_SESSION&&process.env.INGEST_SECRET),botConfigured:!!process.env.TELEGRAM_BOT_TOKEN,aiConfigured:!!(process.env.GROQ_API_KEY||process.env.OPENROUTER_API_KEY),timezone:'Asia/Baghdad',time:new Date().toISOString()}));
app.get('/api/config/:key',async(q,r)=>{try{r.json(await cfg(q.params.key))}catch(e:any){r.status(500).json({error:e.message})}});app.put('/api/config/:key',async(q,r)=>{try{r.json(await setCfg(q.params.key,q.body))}catch(e:any){r.status(500).json({error:e.message})}});
for(const t of ['sources','channels','observations','quarantine','logs','terminology','templates','schedules','published_posts','commodity_observations'])app.get('/api/'+t,async(_q,r)=>{try{r.json(await rows(t))}catch(e:any){r.status(500).json({error:e.message})}});
for(const [route,table] of [['sources','sources'],['channels','channels'],['terminology','terminology'],['templates','templates'],['schedules','schedules']] as const){app.post('/api/'+route,async(q,r)=>{try{let v={...q.body};if(table==='channels'){v.chat_id=v.chat_id||v.username;if(!v.title)v.title=v.username||v.chat_id}if(table==='sources'&&!v.title)v.title=v.username; r.status(201).json(await put(table,v))}catch(e:any){r.status(500).json({error:e.message})}});app.put('/api/'+route+'/:id',async(q,r)=>{try{r.json(await patch(table,q.params.id,q.body))}catch(e:any){r.status(500).json({error:e.message})}});app.delete('/api/'+route+'/:id',async(q,r)=>{try{await del(table,q.params.id);r.json({ok:true})}catch(e:any){r.status(500).json({error:e.message})}})}

app.post('/api/test/extract',async(q,r)=>r.json({items:extract(String(q.body?.text||'')),normalized:norm(String(q.body?.text||''))}));
app.post('/api/test/pipeline',async(q,r)=>{try{const text=String(q.body?.text||'دۆلار 145250 سلێمانی');const items=extract(text);const v=await cfg('validation');r.json({ok:true,items:items.map((x:any)=>({...x,status:x.rate>=v.minRate&&x.rate<=v.maxRate&&x.time_context==='CURRENT'?'VALID':'QUARANTINED'})),supabase:!!db,ingestSecretConfigured:!!process.env.INGEST_SECRET,telegramConfigured:!!process.env.TELEGRAM_SESSION})}catch(e:any){r.status(500).json({error:e.message})}});

app.post('/api/collector/ingest',async(q,r)=>{try{if(process.env.INGEST_SECRET&&q.headers['x-ingest-secret']!==process.env.INGEST_SECRET)return r.status(401).json({error:'unauthorized'});const b:any=q.body||{},text=String(b.text||b.message?.text||b.message?.caption||'');if(!text)return r.status(400).json({error:'empty message'});const username=String(b.chat?.username||b.username||'').replace(/^@/,'');let source:any=null;if(db&&username)source=(await db.from('sources').select('*').eq('username','@'+username).maybeSingle()).data;let raw:any=null;if(db){const rawValue={source_id:source?.id||null,chat_id:String(b.chat?.id||b.chat_id||username||'unknown'),message_id:Number(b.message?.message_id||b.message_id||0),text,telegram_url:b.telegram_url||null,published_at:b.message?.date?new Date(Number(b.message.date)*1000).toISOString():new Date().toISOString(),media:b.media||null};const z=await db.from('raw_messages').insert(rawValue).select('*').single();if(z.error)throw z.error;raw=z.data;await db.from('sources').update({last_message_at:raw.published_at,updated_at:new Date().toISOString()}).eq('id',source?.id||'00000000-0000-0000-0000-000000000000')}
const v=await cfg('validation');const items=extract(text);const saved:any[]=[];for(const o of items){o.source_id=source?.id||null;o.raw_message_id=raw?.id?String(raw.id):null;o.telegram_url=b.telegram_url||null;o.validation_reasons=[];if(Number(o.rate)<Number(v.minRate)||Number(o.rate)>Number(v.maxRate))o.validation_reasons.push('RATE_OUT_OF_RANGE');if(o.time_context!=='CURRENT')o.validation_reasons.push('NOT_CURRENT');o.status=o.validation_reasons.length?'QUARANTINED':'VALID';o.fingerprint=fp(o);if(db){const exists=(await db.from('observations').select('id').eq('fingerprint',o.fingerprint).maybeSingle()).data;if(!exists){const z=await db.from('observations').insert(o).select('*').single();if(z.error)throw z.error;if(z.data)saved.push(z.data);if(o.status==='QUARANTINED'&&z.data)await db.from('quarantine').insert({observation_id:z.data.id,reason:o.validation_reasons.join(','),payload:o})}}else saved.push(o)}await log('INFO','INGEST','Telegram message processed',{source:username,message_id:b.message?.message_id||b.message_id,observations:items.length});r.json({accepted:true,source:username,count:items.length,items,saved,raw_message_id:raw?.id||null})}catch(e:any){await log('ERROR','INGEST',e.message,{stack:e.stack});r.status(500).json({error:e.message})}});

app.get('/api/market/snapshot',async(q,r)=>{try{const data=await currentObs(String(q.query.city||'ALL'));const lf=String(q.query.layer||'ALL');const rr=data.filter((x:any)=>lf==='ALL'||x.market_layer===lf);const g:any={};for(const x of rr){const k=[x.city,x.market_layer,x.dollar_category_normalized,x.rate_role].join('|');(g[k]??=[]).push(Number(x.rate))}const groups=Object.entries(g).map(([key,v]:any)=>{v.sort((a:number,b:number)=>a-b);return{key,city:key.split('|')[0],market_layer:key.split('|')[1],category:key.split('|')[2],rate_role:key.split('|')[3],median:median(v),min:v[0],max:v[v.length-1],range:v[v.length-1]-v[0],count:v.length}});r.json({groups,observations:rr.slice(0,200)})}catch(e:any){r.status(500).json({error:e.message})}});
app.get('/api/market/radar',async(_q,r)=>{try{const p=await cfg('publishing'),window=Number(p.radarWindowMinutes||60),now=await currentObs(),cut=new Date(Date.now()-window*60000);const alerts:any[]=[];for(const cityName of [...new Set(now.map((x:any)=>x.city))]){const cur=now.filter((x:any)=>x.city===cityName).map((x:any)=>Number(x.rate));const prev=now.filter((x:any)=>x.city===cityName&&new Date(x.observed_at)<cut).map((x:any)=>Number(x.rate));if(cur.length&&prev.length){const a=median(cur)!,b=median(prev)!,d=a-b;if(Math.abs(d)>=Number(p.radarDelta||250))alerts.push({city:cityName,current:a,previous:b,movement:d,direction:d>0?'UP':'DOWN',sources:new Set(now.filter((x:any)=>x.city===cityName).map((x:any)=>x.source_id)).size})}}r.json({threshold:p.radarDelta||250,windowMinutes:window,alerts})}catch(e:any){r.status(500).json({error:e.message})}});
app.get('/api/market/history',async(q,r)=>{try{if(!db)return r.json([]);const hours=Math.min(Number(q.query.hours||24),2160),since=new Date(Date.now()-hours*3600000).toISOString();let x=db.from('observations').select('city,market_layer,dollar_category_normalized,rate_role,rate,observed_at,source_id,confidence').eq('status','VALID').eq('time_context','CURRENT').gte('observed_at',since).order('observed_at',{ascending:true});if(q.query.city)x=x.eq('city',String(q.query.city));const {data,error}=await x.limit(5000);if(error)throw error;r.json(data||[])}catch(e:any){r.status(500).json({error:e.message})}});
app.get('/api/analytics',async(_q,r)=>{try{if(!db)return r.json({messageCount:0,observationCount:0,validCount:0,quarantineCount:0,publishedCount:0,sources:[]});const[o,q,raw,pub,s]=await Promise.all([db.from('observations').select('status,source_id,confidence,observed_at'),db.from('quarantine').select('id',{count:'exact',head:true}),db.from('raw_messages').select('id',{count:'exact',head:true}),db.from('published_posts').select('id',{count:'exact',head:true}),db.from('sources').select('*')]);const d=o.data||[];r.json({messageCount:raw.count||0,observationCount:d.length,validCount:d.filter((x:any)=>x.status==='VALID').length,quarantineCount:q.count||0,publishedCount:pub.count||0,sources:(s.data||[]).map((s:any)=>{const a=d.filter((x:any)=>x.source_id===s.id);return{username:s.username,title:s.title,count:a.length,valid:a.filter((x:any)=>x.status==='VALID').length,quarantine:a.filter((x:any)=>x.status==='QUARANTINED').length,validity:a.length?a.filter((x:any)=>x.status==='VALID').length/a.length:0,confidence:a.length?a.reduce((n:number,x:any)=>n+Number(x.confidence||0),0)/a.length:0,last:a.sort((a:any,b:any)=>+new Date(b.observed_at)-+new Date(a.observed_at))[0]?.observed_at||s.last_message_at||null}})})}catch(e:any){r.status(500).json({error:e.message})}});
app.get('/api/analytics/history',async(q,r)=>{try{if(!db)return r.json([]);const hours=Math.min(Number(q.query.hours||24),2160),since=new Date(Date.now()-hours*3600000).toISOString();const {data,error}=await db.from('observations').select('city,market_layer,rate,rate_role,observed_at,source_id,confidence').eq('status','VALID').gte('observed_at',since).order('observed_at',{ascending:true}).limit(5000);if(error)throw error;r.json(data||[])}catch(e:any){r.status(500).json({error:e.message})}});
app.get('/api/analytics/source-performance',async(_q,r)=>{try{const s=await rows('sources'),o=await rows('observations',5000);r.json(s.map((x:any)=>{const a=o.filter((z:any)=>z.source_id===x.id);return{...x,messages:a.length,valid:a.filter((z:any)=>z.status==='VALID').length,quarantine:a.filter((z:any)=>z.status==='QUARANTINED').length,validity:a.length?a.filter((z:any)=>z.status==='VALID').length/a.length:0,avgConfidence:a.length?a.reduce((n:number,z:any)=>n+Number(z.confidence||0),0)/a.length:0,lastObservation:a.sort((a:any,b:any)=>+new Date(b.observed_at)-+new Date(a.observed_at))[0]?.observed_at||x.last_message_at||null}}))}catch(e:any){r.status(500).json({error:e.message})}});

app.post('/api/ai/editorial',async(q,r)=>{try{const text=await editorial(String(q.body?.reportType||'LIVE'));r.json({ok:true,text})}catch(e:any){r.status(500).json({error:e.message})}});
app.post('/api/ai/extract',async(q,r)=>{try{const result=await ai(String(q.body?.text||''),'Extract Iraqi market observations as strict JSON. Never guess. Preserve عرض and طلب as raw labels. Never infer BUY/SELL. Return observations with city, market_layer, rate, rate_role, time_context, confidence, evidence_text.');let items:any;try{items=JSON.parse(result)}catch{items={raw:result}}r.json({ok:true,items})}catch(e:any){r.status(500).json({error:e.message})}});
app.get('/api/config/bot',async(_q,r)=>r.json({configured:!!process.env.TELEGRAM_BOT_TOKEN,webhookConfigured:!!process.env.TELEGRAM_WEBHOOK_SECRET}));
app.post('/api/telegram/test',async(_q,r)=>{try{if(!process.env.TELEGRAM_BOT_TOKEN)return r.status(400).json({configured:false,error:'TELEGRAM_BOT_TOKEN missing'});const x:any=await(await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/getMe`)).json();r.json({configured:true,connected:!!x.ok,bot:x.result||null,lastCheck:new Date().toISOString()})}catch(e:any){r.status(500).json({error:e.message})}});
app.post('/api/telegram/set-webhook',async(q,r)=>{try{const token=process.env.TELEGRAM_BOT_TOKEN;if(!token)throw new Error('TELEGRAM_BOT_TOKEN missing');const url=String(q.body?.url||`${process.env.APP_URL||''}/api/telegram/webhook`);if(!url.startsWith('http'))throw new Error('APP_URL or url required');const body:any={url};if(process.env.TELEGRAM_WEBHOOK_SECRET)body.secret_token=process.env.TELEGRAM_WEBHOOK_SECRET;const x:any=await(await fetch(`https://api.telegram.org/bot${token}/setWebhook`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})).json();r.json(x)}catch(e:any){r.status(500).json({error:e.message})}});
app.post('/api/telegram/webhook',async(q,r)=>{try{if(process.env.TELEGRAM_WEBHOOK_SECRET&&q.headers['x-telegram-bot-api-secret-token']!==process.env.TELEGRAM_WEBHOOK_SECRET)return r.status(401).json({error:'unauthorized'});const m:any=q.body?.message||q.body?.channel_post;if(!m?.text)return r.json({ok:true});const chat=String(m.chat?.id||'');const cmd=String(m.text).trim().split(/\s+/)[0].toLowerCase();if(cmd==='/price'){const o=await currentObs();const m=median(o.map((x:any)=>Number(x.rate)));await sendTelegram(chat,m?`💵 USD/IQD: ${m.toLocaleString('en-US')} IQD`:'No current verified price.')}else if(cmd==='/source'){const s=await rows('sources');await sendTelegram(chat,s.map((x:any)=>`• ${x.username} — ${x.enabled?'ON':'OFF'}`).join('\n')||'No sources.')}else if(cmd==='/radar'){const p=await cfg('publishing'),o=await currentObs();await sendTelegram(chat,`📡 Radar threshold: ${p.radarDelta||250} IQD\nCurrent verified observations: ${o.length}`)}r.json({ok:true})}catch(e:any){await log('ERROR','TELEGRAM_WEBHOOK',e.message);r.status(500).json({error:e.message})}});
app.post('/api/publish/:type',async(q,r)=>{try{r.json(await publish(String(q.params.type||'LIVE').toUpperCase(),q.body?.channel))}catch(e:any){r.status(500).json({error:e.message})}});
app.post('/api/scheduler/run',async(q,r)=>{try{const type=String(q.body?.type||'LIVE').toUpperCase();r.json(await publish(type,q.body?.channel))}catch(e:any){r.status(500).json({error:e.message})}});
app.get('/api/backup/config',async(_q,r)=>{const o:any={};for(const k of ['validation','polling','publishing','market','ai','commodities','commands'])o[k]=await cfg(k);r.setHeader('Content-Disposition','attachment; filename="nova-dollar-config.json"');r.json(o)});
if(process.env.NODE_ENV!=='vercel')app.listen(PORT,()=>console.log(`Nova Dollar API listening on ${PORT}`));
export default app;
