create extension if not exists pgcrypto;
create table if not exists app_config(key text primary key,value jsonb not null,updated_at timestamptz not null default now());
create table if not exists sources(id uuid primary key default gen_random_uuid(),username text unique not null,title text,priority text not null default 'NORMAL',enabled boolean not null default true,regex_extraction boolean not null default true,ai_extraction boolean not null default true,publish_enabled boolean not null default false,created_at timestamptz not null default now());
create table if not exists channels(id uuid primary key default gen_random_uuid(),title text not null,username text unique not null,enabled boolean not null default true,created_at timestamptz not null default now());
create table if not exists raw_messages(id uuid primary key default gen_random_uuid(),source_id uuid references sources(id) on delete set null,telegram_message_id bigint,message_text text not null,telegram_url text,posted_at timestamptz,raw_payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists raw_messages_source_time_idx on raw_messages(source_id,posted_at desc);
create table if not exists observations(id uuid primary key default gen_random_uuid(),source_id uuid references sources(id) on delete set null,raw_message_id uuid references raw_messages(id) on delete set null,telegram_url text,city text not null default 'UNKNOWN',market text,market_layer text not null default 'UNKNOWN',currency text not null default 'IQD',quote_currency text not null default 'USD',denomination numeric,rate numeric,quote_label_raw text,quote_label_normalized text,dollar_category_raw text,dollar_category_normalized text not null default 'STANDARD_MIX',time_context text not null default 'CURRENT',rate_role text not null default 'UNKNOWN',numeric_role text not null default 'RATE',confidence numeric not null default 0,evidence_text text,evidence_start integer,evidence_end integer,status text not null default 'CANDIDATE',validation_reasons text[] default '{}',fingerprint text unique,observed_at timestamptz not null default now(),created_at timestamptz not null default now());
create index if not exists observations_city_time_idx on observations(city,observed_at desc);create index if not exists observations_group_idx on observations(city,market_layer,dollar_category_normalized,rate_role,observed_at desc);create index if not exists observations_status_time_idx on observations(status,time_context,observed_at desc);
create table if not exists commodity_observations(id uuid primary key default gen_random_uuid(),source_id uuid references sources(id) on delete set null,raw_message_id uuid references raw_messages(id) on delete set null,commodity text not null,product_type text,subtype text,weight_g numeric,purity numeric,city text,market_layer text,rate_role text,currency text,price numeric,confidence numeric,evidence_text text,fingerprint text unique,status text not null default 'CANDIDATE',validation_reasons text[] default '{}',observed_at timestamptz not null default now(),created_at timestamptz not null default now());
create table if not exists quarantine(id uuid primary key default gen_random_uuid(),observation_id uuid references observations(id) on delete cascade,reason text not null,payload jsonb not null,status text not null default 'OPEN',reviewed_at timestamptz,created_at timestamptz not null default now());
create table if not exists terminology(id uuid primary key default gen_random_uuid(),raw_term text not null,normalized_term text not null,category text,language text,source_id uuid references sources(id) on delete cascade,enabled boolean not null default true,confidence numeric default 1,notes text,created_at timestamptz not null default now());
create table if not exists templates(id uuid primary key default gen_random_uuid(),name text not null,body text not null,enabled boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists schedules(id uuid primary key default gen_random_uuid(),name text not null,schedule_type text not null default 'DAILY',expression text not null,timezone text not null default 'Asia/Baghdad',enabled boolean not null default true,template_id uuid references templates(id) on delete set null,channel_id uuid references channels(id) on delete cascade,last_run_at timestamptz,created_at timestamptz not null default now());
create table if not exists published_posts(id uuid primary key default gen_random_uuid(),channel_id uuid references channels(id) on delete set null,telegram_message_id bigint,text text,status text not null,error text,created_at timestamptz not null default now());
create table if not exists logs(id uuid primary key default gen_random_uuid(),level text not null,kind text not null,message text not null,meta jsonb default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists automation_runs(id uuid primary key default gen_random_uuid(),run_key text not null unique,created_at timestamptz not null default now());
create index if not exists automation_runs_created_idx on automation_runs(created_at desc);
insert into app_config(key,value) values
('validation','{"enabled":true,"minRate":140000,"maxRate":165000,"warningOnly":false,"anomalyEnabled":true,"anomalyDelta":3000,"anomalyWindowMinutes":10,"freshnessMinutes":180}'),
('polling','{"enabled":true,"peakIntervalMinutes":2,"normalIntervalMinutes":5,"nightIntervalMinutes":15,"timezone":"Asia/Baghdad","peakStart":"10:00","peakEnd":"18:00","quietDays":[5,0]}'),
('publishing','{"enabled":false,"livePriceEnabled":true,"minConfidence":0.8,"minIndependentSources":1,"maxPostsPerHour":30,"quietStart":"23:00","quietEnd":"08:00","radarEnabled":true,"radarDelta":250,"radarWindowMinutes":60,"openTime":"10:00","closeTime":"17:30"}'),
('commands','{"price":true,"source":true}'),
('market','{"defaultCity":"SULAYMANIYAH","headlineCategory":"STANDARD_MIX","radarDelta":250,"radarWindowMinutes":60,"freshnessMinutes":180}'),
('ai','{"enabled":true,"provider":"groq","endpoint":"https://api.groq.com/openai/v1/chat/completions","model":"llama-3.3-70b-versatile","temperature":0,"maxTokens":2200}'),
('commodities','{"silverKgEnabled":false,"dubaiLira72gEnabled":false,"silverMinConfidence":0.75,"liraMinConfidence":0.75}')
on conflict(key) do nothing;
insert into sources(username,title,priority,enabled,regex_extraction,ai_extraction,publish_enabled) values
('@pashagoldd','Pasha Gold','HIGH',true,true,true,false),('@borsat_alkfah','Borsa Al Kifah','HIGH',true,true,true,false),('@Borsa_Erbil','Borsa Erbil','HIGH',true,true,true,false),('@PMCgroup','PMC Group','HIGH',true,true,true,false),('@nrxidolar','Nrx i Dolar','HIGH',true,true,true,false),('@iraqborsa','Iraq Borsa','HIGH',true,true,true,false),('@RaprsyWnrx','Raprsy W Nrx','NORMAL',true,true,true,false),('@borsakurdstan','Borsa Kurdstan','HIGH',true,true,true,false),('@httpswyTu0W4VrKZkMGZi','Configured Source','NORMAL',true,true,true,false),('@Ranyadollar','Ranya Dollar','HIGH',true,true,true,false),('@kurddolar','Kurd Dollar','HIGH',true,true,true,false),('@NrxiDraw24','Nrxi Draw24','NORMAL',true,true,true,false),('@nrxidraw852','Nrx i Draw852','NORMAL',true,true,true,false),('@YarGold_Co','Yar Gold Co','NORMAL',true,true,true,false)
on conflict(username) do nothing;
insert into terminology(raw_term,normalized_term,category,language) values
('عرض','عرض','QUOTE_LABEL','ar'),('طلب','طلب','QUOTE_LABEL','ar'),('بيع','SELL','SELL_CONTEXT','ar'),('فرۆشتن','SELL','SELL_CONTEXT','ku'),('شراء','BUY','BUY_CONTEXT','ar'),('کڕین','BUY','BUY_CONTEXT','ku'),('پێنجی','5000_IQD_CATEGORY','DOLLAR_CATEGORY','ku'),('خمسات','5000_IQD_CATEGORY','DOLLAR_CATEGORY','ar'),('دەیی','10000_IQD_CATEGORY','DOLLAR_CATEGORY','ku'),('عشر','10000_IQD_CATEGORY','DOLLAR_CATEGORY','ar'),('سوور','25000_IQD_CATEGORY','DOLLAR_CATEGORY','ku'),('أحمر','25000_IQD_CATEGORY','DOLLAR_CATEGORY','ar'),('سلێمانی','SULAYMANIYAH','LOCATION','ku'),('السليمانية','SULAYMANIYAH','LOCATION','ar'),('هەولێر','ERBIL','LOCATION','ku'),('أربيل','ERBIL','LOCATION','ar'),('بغداد','BAGHDAD','LOCATION','mixed'),('مووسڵ','MOSUL','LOCATION','ku'),('الموصل','MOSUL','LOCATION','ar'),('نینەوا','MOSUL','LOCATION','ku'),('نينوى','MOSUL','LOCATION','ar'),('بەسرە','BASRA','LOCATION','ku'),('البصرة','BASRA','LOCATION','ar'),('بورصة','BOURSE','MARKET_LAYER','mixed'),('صيرفات','EXCHANGE_OFFICES','MARKET_LAYER','ar'),('مكاتب','EXCHANGE_OFFICES','MARKET_LAYER','ar'),('بازاڕ','LOCAL_MARKET','MARKET_LAYER','ku'),('سوق','LOCAL_MARKET','MARKET_LAYER','ar'),('الآن','NOW','TIME','ar'),('هسه','NOW','TIME','ku'),('دوێنێ','HISTORICAL','TIME','ku'),('أمس','HISTORICAL','TIME','ar'),('غداً','FORECAST','TIME','ar'),('پێشبینی','FORECAST','TIME','ku')
on conflict do nothing;
