import 'dotenv/config';
import { TelegramClient } from 'telegram';
import { StringSession } from 'telegram/sessions/index.js';
import { NewMessage } from 'telegram/events/index.js';
const apiId=Number(process.env.TELEGRAM_API_ID||0);const apiHash=process.env.TELEGRAM_API_HASH||'';const session=process.env.TELEGRAM_SESSION||'';const ingestUrl=process.env.INGEST_URL||'http://localhost:8787/api/collector/ingest';const ingestSecret=process.env.INGEST_SECRET||'';const sources=(process.env.MTPROTO_SOURCES||'pashagoldd,borsat_alkfah,Borsa_Erbil,PMCgroup,nrxidolar,iraqborsa,RaprsyWnrx,borsakurdstan,httpswyTu0W4VrKZkMGZi,Ranyadollar,kurddolar,NrxiDraw24,nrxidraw852,YarGold_Co').split(',').map(x=>x.trim().replace(/^@/,'')).filter(Boolean);
if(!apiId||!apiHash||!session||!ingestSecret)throw new Error('TELEGRAM_API_ID, TELEGRAM_API_HASH, TELEGRAM_SESSION and INGEST_SECRET are required');
const client=new TelegramClient(new StringSession(session),apiId,apiHash,{connectionRetries:5});
async function main(){await client.connect();const me=await client.getMe();console.log(`MTProto collector connected as ${me.username?'@'+me.username:me.id}`);const entities:any[]=[];for(const username of sources){try{entities.push(await client.getEntity(username));console.log(`Watching @${username}`)}catch(e:any){console.error(`Cannot resolve @${username}: ${e.message}`)}}client.addEventHandler(async(event:any)=>{const msg=event.message;if(!msg?.message)return;const chat=await msg.getChat();const username=String((chat as any)?.username||'').replace(/^@/,'');if(!username||!sources.includes(username))return;const payload={chat:{id:String((chat as any).id),username:'@'+username,title:String((chat as any).title||username)},message:{message_id:Number(msg.id),date:Number(msg.date||Math.floor(Date.now()/1000)),text:String(msg.message||''),caption:String(msg.message||'')}};try{const r=await fetch(ingestUrl,{method:'POST',headers:{'content-type':'application/json','x-ingest-secret':ingestSecret},body:JSON.stringify(payload)});if(!r.ok)console.error(`Ingest failed @${username}: ${r.status} ${await r.text()}`);else console.log(`Ingested @${username} message ${msg.id}`)}catch(e:any){console.error(`Ingest error @${username}: ${e.message}`)}},new NewMessage({chats:entities}));console.log('Listening for new source posts...');await new Promise(()=>{})}
main().catch(e=>{console.error(e);process.exit(1)});
